package.json
src/docs/constants.ts
src/docs/examples/ButtonExamples.svelte
src/lib/components/Card.svelte
src/lib/components/Icon.svelte
src/routes/+page.svelte
src/routes/examples/[component]/+page.svelte
tailwind.config.ts

Adjust background and border colors for the card component.

feat: card styles

---

src/docs/constants.ts
src/lib/components/CloseButton/CloseButton.svelte
src/lib/index.ts
src/lib/types.ts
src/routes/examples/close-button/+page.svelte

Add a `CloseButton` component.

feat: close button

---

src/docs/constants.ts
src/lib/components/Link/Link.svelte
src/lib/index.ts
src/routes/examples/link/+page.svelte

feat: link

---

src/docs/constants.ts
src/lib/components/Heading/Heading.svelte
src/lib/components/SupporterBadge/SupporterBadge.svelte
src/lib/index.ts
src/routes/examples/supporter-badge/+page.svelte

Add a `SupporterBadge` component

feat: supporter badge

---

src/docs/constants.ts
src/lib/components/Code/Code.svelte
src/lib/index.ts
src/routes/components/code/+page.svelte
src/routes/components/code/ColorExample.svelte
src/routes/components/code/FilledExample.svelte
src/routes/components/code/SizeExample.svelte

feat: code component

---

src/docs/components/ComponentCard.svelte
src/routes/+page.svelte

Make the button component softer 
| Before | After |
| - | - |
| <img width="1291" alt="image" src="https://github.com/user-attachments/assets/49451254-9d5c-4c06-a7cf-e60757c7e18a" /> | <img width="1378" alt="image" src="https://github.com/user-attachments/assets/38472d16-61ed-4c3e-863b-4c83a3c6b0dd" /> |

feat: main page styling

---

src/lib/components/Alert/Alert.svelte
src/routes/components/alert/+page.svelte
src/routes/components/alert/EventExample.svelte

feat: closable alerts

---

src/lib/components/Alert/Alert.svelte
src/routes/components/alert/BasicExample.svelte

feat: alert sizes

---

src/lib/components/Heading/Heading.svelte

Allow pass any props that can be added to a heading element.

fix: heading props

---

src/lib/components/Alert/Alert.svelte
src/routes/components/alert/BasicExample.svelte
src/routes/components/alert/ColorExample.svelte
src/routes/components/alert/CustomIconExample.svelte

- Vertically center the description when there isn't a title
- Change the default info icon
- Add an option to turn the icon off

feat: alert improvements

---

src/lib/components/Form/Input.svelte
src/lib/components/IconButton/IconButton.svelte
src/lib/components/Switch/Switch.svelte
src/lib/internal/Button.svelte
src/routes/components/switch/FormExample.svelte

- Fix switch state management issues
- Fix switch button submit
- Fix IconButton sizing/padding percentages

fix: switch and buttons

---

src/lib/components/Modal/Modal.svelte
src/routes/components/modal/+page.svelte
src/routes/components/modal/IconExample.svelte

Add icons to modals (defaults to showing the Immich logo).
```html
<Modal icon={mdiDownload} />
<Modal icon={true} />
<Modal icon={false} />
```

feat: modal icon

---

src/lib/components/Heading/Heading.svelte
src/lib/components/Modal/Modal.svelte

Switched out blur backdrop for clear backdrop to make the modal pop, and modifications to the styling

chore: modal styling

---

src/app.css

Make background slightly darker on light mode and slightly lighter in dark mode to improve readability of text

chore: colors tunning

---

package.json
src/docs/components/Navbar.svelte
src/lib/components/AppShell/AppShellSidebar.svelte
src/lib/components/Form/PasswordInput.svelte
src/lib/components/Navbar/NavbarItem.svelte
src/lib/utils.ts
src/routes/+layout.svelte
src/routes/components/app-shell/BasicExample.svelte

Open and close the sidebar via `bind:open`

feat: better sidebar control

---

package.json

Looks like I need these after all.

fix: import paths

---

src/lib/common/context.svelte.ts
src/lib/components/Form/Checkbox.svelte
src/lib/components/Form/Input.svelte
src/lib/components/Switch/Switch.svelte
src/lib/components/Text/Text.svelte
src/lib/types.ts
src/routes/components/checkbox/BasicExample.svelte
src/routes/components/input/BasicExample.svelte
src/routes/components/switch/FormExample.svelte

Add a `description` prop to the `<Field>` component, which can be used to add descriptions to form elements.

feat: field description

---

renovate.json

chore: remove renovate schedule override

---

src/lib/internal/Button.svelte

Not sure why they used to have this but not anymore.

fix: button cursor

---

src/lib/components/Button/Button.svelte
src/lib/components/Card/Card.svelte
src/lib/components/Modal/Modal.svelte
src/lib/index.ts
src/routes/components/modal/IconExample.svelte

- Add the option to enable/disable `closeOnEsc`
- Add the option to enable/disable `closeOnBackdropClick`
- Add the option to provide a custom `<ModalHeader>`

feat: custom modal header

---

src/lib/components/Link/Link.svelte
src/lib/components/Navbar/NavbarItem.svelte
src/lib/internal/Button.svelte
src/lib/types.ts

Add the option to mark a navbar item or button link as external.

feat: external buttons and navbar items

---

src/docs/components/ComponentPage.svelte
src/docs/constants.ts
src/lib/components/SiteMetadata/SiteMetadata.svelte
src/lib/index.ts
src/lib/utilities/common.ts
src/routes/+layout.ts
src/routes/+page.svelte
src/routes/components/alert/+page.svelte
src/routes/components/app-shell/+page.svelte
src/routes/components/avatar/+page.svelte
src/routes/components/button/+page.svelte
src/routes/components/checkbox/+page.svelte
src/routes/components/close-button/+page.svelte
src/routes/components/code-block/+page.svelte
src/routes/components/code/+page.svelte
src/routes/components/command-palette/+page.svelte
src/routes/components/confirm-modal/+page.svelte
src/routes/components/field/+page.svelte
src/routes/components/helper-text/+page.svelte
src/routes/components/input/+page.svelte
src/routes/components/multi-select/+page.svelte
src/routes/components/multi-select/BasicExample.svelte
src/routes/components/password-input/+page.svelte
src/routes/components/select/+page.svelte
src/routes/components/select/BasicExample.svelte
src/routes/components/switch/+page.svelte
svelte.config.js

feat: prerender

---

src/lib/components/SiteMetadata/SiteMetadata.svelte
src/lib/utilities/common.spec.ts
src/lib/utilities/common.ts
src/routes/+layout.svelte
src/routes/+page.ts
svelte.config.js

Fix a case when site metadata would duplicate the page description.

fix: site metadata
